#' calcStochClocks
#'
#' @description An R-function to estimate the DNAm-Age according to one of 3 stochastic epigenetic clocks (StocH, StocZ, StocP). These are stochastic analogues of the Horvath, Zhang and Levine/PhenoAge clocks. They are made up of exactly the same CpGs as the original clocks but were built from artificial cohorts generated by a stochastic process of age-related DNAm-change accrual. Although they were built from young and old sorted monocyte samples from the MESA study, their predictive ability is largely independent of the immune cell type or if evaluated in whole blood. This is because DNAm data is standardized before application of the clock. The stochastic clocks may be a useful addition to the original clocks, as a way of assessing if specific age-accelerations of the original clocks could be driven by an underlying stochastic process or not. This could potential shed insight on the biological mechanism underlying biological processes that are linked to the phenotypes exhibit age-acceleration (or deceleration).

#' @param data.m normalized DNAm data beta-valued matrix with rownames labeling CpGs and columns labeling samples.
#' @param ages.v Optional argument representing the chronological ages or surrogates thereof of the samples. Vector must be of same length as the number of samples.

#' @return #### A list containing the following entries
#### mage: a list of 3 vectors containing the predicted DNAm-ages for StocH, StocP and StocZ clocks
#### eaa: a list of 3 vectors containing the extrinsic age-acceleration for StocH, StocP and StocZ clocks
#### iaa: a list of 3 vectors containing the intrinsic age-acceleration for StocH, StocP and StocZ clocks
#' @export

### RunStochClocks.R
#### Author: Andrew E Teschendorff (andrew@sinh.ac.cn) & Tong Huige (tonghuige2021@sinh.ac.cn)
#### Date: 20th Sep 2023
#### Copyright 2023 Andrew Teschendorff
#### Copyright permission: RunStochClocks is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License version-3 as published by the Free Software  Foundation. epiTOC2 is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details (http://ww.gnu.org/licenses/).


#### DESCRIPTION
#### An R-function to estimate the DNAm-Age according to one of 3 stochastic epigenetic clocks (StocH, StocZ, StocP). These are stochastic analogues of the Horvath, Zhang and Levine/PhenoAge clocks. They are made up of exactly the same CpGs as the original clocks but were built from artificial cohorts generated by a stochastic process of age-related DNAm-change accrual. Although they were built from young and old sorted monocyte samples from the MESA study, their predictive ability is largely independent of the immune cell type or if evaluated in whole blood. This is because DNAm data is standardized before application of the clock. The stochastic clocks may be a useful addition to the original clocks, as a way of assessing if specific age-accelerations of the original clocks could be driven by an underlying stochastic process or not. This could potential shed insight on the biological mechanism underlying biological processes that are linked to the phenotypes exhibit age-acceleration (or deceleration).

#### REQUIRED OBJECTS:
#### glmStocALL.Rd: a list object containing the 3 stochastic clocks as glmnet objects
#### libraries: glmnet, EpiDISH (recommended for IAA calculation)

#### INPUT:
#### data.m: normalized DNAm data beta-valued matrix with rownames labeling CpGs and columns labeling samples.
#### ages.v: Optional argument representing the chronological ages or surrogates thereof of the samples. Vector must be of same length as the number of samples.

#### OUPTUT:
#### A list containing the following entries
#### mage: a list of 3 vectors containing the predicted DNAm-ages for StocH, StocP and StocZ clocks
#### eaa: a list of 3 vectors containing the extrinsic age-acceleration for StocH, StocP and StocZ clocks
#### iaa: a list of 3 vectors containing the intrinsic age-acceleration for StocH, StocP and StocZ clocks

calcStochClocks <- function(data.m, datPheno, ages.v = NULL, refM.m = NULL) {
  library(glmnet)
  library(EpiDISH)

  data.m <- t(data.m)

  data(glmStocALL) ## load in stochastic clock information
  estF.m <- NULL
  if (!is.null(refM.m)) {
    estF.m <- epidish(data.m, ref = refM.m, method = "RPC", maxit = 500)$est
  }
  predMage.lv <- list()
  eaa.lv <- list()
  iaa.lv <- list()
  for (c in 1:length(glmStocALL.lo)) {
    glm.o <- glmStocALL.lo[[c]]
    coef.m <- coef(glm.o)
    intC <- coef.m[1, ncol(coef.m)] ### intercept term
    coef.v <- coef.m[-1, ncol(coef.m)] ### estimated regression coefficients
    commonCpGs.v <- intersect(names(coef.v), rownames(data.m))
    rep.idx <- match(commonCpGs.v, names(coef.v))
    map.idx <- match(commonCpGs.v, rownames(data.m))
    predMage.lv[[c]] <- as.vector(intC + matrix(coef.v[rep.idx], nrow = 1) %*% data.m[map.idx, ])
    if (!is.null(ages.v)) {
      eaa.lv[[c]] <- lm(predMage.lv[[c]] ~ ages.v)$res
      if (!is.null(refM.m)) {
        iaa.lv[[c]] <- lm(predMage.lv[[c]] ~ ages.v + estF.m)$res
      }
    }
  }

  df <- data.frame(
    StocH = predMage.lv[[1]],
    StocP = predMage.lv[[2]],
    StocZ = predMage.lv[[3]]
  )

  datPheno <- cbind(datPheno, df)

  # return(list(mage=predMage.lv,eaa=eaa.lv,iaa=iaa.lv,estF=estF.m));
  return(datPheno)
}
